---
- name: Setup Docker and Run Container
  hosts: all
  become: yes

  tasks:
    #  Update the package manager
    - name: Update apt packages
      apt:
        update_cache: yes

    #  Install Docker dependencies
    - name: Install dependencies
      apt:
        name: 
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    #  Add Docker's official GPG key
    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    #  Add Docker repository
    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    #  Install Docker
    - name: Install Docker
      apt:
        name: docker-ce
        state: latest

    #  Ensure Docker is started and enabled
    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes

    #  Pull the image from Docker Hub
    - name: Pull Docker image
      docker_image:
        name: faresahmed74/flask-weather-app
        tag: latest
        source: pull

    #  Run a container using the pulled image
    - name: Run Docker container
      docker_container:
        name: my-container
        image: faresahmed74/flask-weather-app:latest
        state: started
        ports:
          - "5000:5000"  

